spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

rabbitmq:
  exchange: rabbit.mq.exchange
  routing-key: rabbit.mq.routing.key
  queue: rabbit.mq.queue

  #Artemis Configuration
  artemis:
    mode: native
    host: localhost
    port: 8161
    user: artemis
    password: artemis