spring:
  rabbitmq:
    host: ${CLOUD_RABBITMQ_HOST_NAME}
    port: ${CLOUD_RABBITMQ_PORT}
    username: ${CLOUD_RABBITMQ_USERNAME}
    password: ${CLOUD_RABBITMQ_PASSWORD}
    virtual-host: ${CLOUD_RABBITMQ_VIRTUAL_HOST}
    ssl:
      enabled: true

rabbitmq:
  exchange: rabbit.mq.exchange
  routing-key: rabbit.mq.routing.key
  queue: rabbit.mq.queue