package com.moneyfi.apigateway.util.enums;

public enum ReasonEnum {
    BLOCK_ACCOUNT,
    PASSWORD_CHANGE,
    FORGOT_PASSWORD,
    NAME_CHANGE,
    UNBLOCK_ACCOUNT,
    DELETE_ACCOUNT,
    ACCOUNT_RETRIEVAL,
    PHONE_NUMBER_CHANGE,
    USER_RAISED_REQUEST_IGNORED,
    FORGOT_USERNAME;
}
