spring:
  application:
    name:
      MoneyFi-expense
  datasource:
    url: jdbc:sqlserver://${RDS_HOSTNAME:localhost}:${RDS_PORT:1433};databaseName=${RDS_DB_NAME:moneyfi_db};encrypt=true;trustServerCertificate=true
    username: ${RDS_USERNAME:sa}
    password: ${RDS_PASSWORD:admin@123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port:
    8200
