spring:
  application:
    name:
      MoneyFi-income
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true

server:
  port:
    8100

account:
  statement:
    admin:
      pdf:
        password: ${ADMIN_PDF_PASSWORD}
