INSERT INTO reason_code_table (id, name)
VALUES (1, 'Block Account'),
       (2, 'Password Change'),
       (3, 'Name Change'),
       (4, 'Unblock Account'),
       (5, 'Delete Account'),
       (6, 'Account retrieval'),
       (7, 'Phone Number Change'),
       (8, 'Ignore User Request'),
       (9, 'Gmail Sync Request Type'),
       (10, 'Forgot Username'),
       (11, 'Admin Creation'),
       (12, 'Admin Update'),
       (13, 'Admin Block'),
       (14, 'Admin Unblock'),
       (15, 'Admin Delete'),
       (16, 'Admin Retrieval');