spring:
  application:
    name: MoneyFi-api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: MoneyFi-user
          uri: lb://MoneyFi-user
          predicates:
            - Path=/api/v1/user-service/**
        - id: MoneyFi-Transaction
          uri: lb://MoneyFi-Transaction
          predicates:
            - Path=/api/v1/transaction/**
        - id: MoneyFi-wealth-core
          uri: lb://MoneyFi-wealth-core
          predicates:
            - Path=/api/v1/wealth-core/**

jwt:
  secret: ekhfjulewfsuydg342fhdarewugafhs69aufg7efesdaf

cors:
  allowed-origins: ${ALLOWED_ORIGINS}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true

server:
  port: 8765
